-- CODIGO PARA MYSQL

CREATE TABLE usuarios (
    id_usuario INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(200) NOT NULL,
    senha VARCHAR(200) NOT NULL,
    tipo INT(1) NOT NULL
)

-- 0 É ADMIN
-- 1 É CAIXA